### ISSUE TITLE
Release as a NET standard library

### ISSUE THREAD

**Issue by PeteyPii** [macote/Winook#17]
PoE Sidekick is also looking into using Winook to deal with mouse lag from mouse wheel event hooks but we currently can't try it out since it is running on NET framework

**Comment by macote** [comment]
Hi,

Thank you for the interest you have in Winook. I agree that targeting .NET Standard is a welcomed addition. 

The challenge I have with this is updating my nuspec file so that I can distribute a Winook package that works with both .NET Framework and .NET Core. I think there are significant differences between how this is handled (`packages.config` vs `PackageReference`). The main road block is the fact that Winook uses pre-compiled support files that need to be distributed as well. I can spend some time on that matter, but if you already know how to make it work, please feel free to share this with me.

**Comment by PeteyPii** [comment]
My knowledge of C# and its package ecosystem is limited. I was following this guide: https://www.michaeltaylorp3.net/porting-a-net-framework-library-to-net-standard/ and it does mention having to create a new package  (IIUC). Maybe it will just be easier to declare the current code as the final version of `Winook` and create a new package called `WinookStandard` (or something else).

**Comment by macote** [comment]
Sounds good, I'll check the guide and try it out. Thanks.

**Comment by macote** [comment]
Can you please try [this](https://www.nuget.org/packages/Winook/1.0.1-beta) out?
